// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk21cpOmqjl46O8RJrZlelK41IvAOiILM',
    appId: '1:248567726483:web:b4c3181eef166a1dd9e866',
    messagingSenderId: '248567726483',
    projectId: 'projet-e9263',
    authDomain: 'projet-e9263.firebaseapp.com',
    storageBucket: 'projet-e9263.firebasestorage.app',
    measurementId: 'G-4FCY07T7DT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDWsXhSiAHGONn5uxr7W1Thfd8MMJTDSQ',
    appId: '1:248567726483:android:8f02a5a078d22892d9e866',
    messagingSenderId: '248567726483',
    projectId: 'projet-e9263',
    storageBucket: 'projet-e9263.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC-aJ9SntbZWXEYAdX9ZHKaCaAYr4r0ak',
    appId: '1:248567726483:ios:b9c7fbc86dc7f7ced9e866',
    messagingSenderId: '248567726483',
    projectId: 'projet-e9263',
    storageBucket: 'projet-e9263.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC-aJ9SntbZWXEYAdX9ZHKaCaAYr4r0ak',
    appId: '1:248567726483:ios:b9c7fbc86dc7f7ced9e866',
    messagingSenderId: '248567726483',
    projectId: 'projet-e9263',
    storageBucket: 'projet-e9263.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAk21cpOmqjl46O8RJrZlelK41IvAOiILM',
    appId: '1:248567726483:web:d1e58308b4d84883d9e866',
    messagingSenderId: '248567726483',
    projectId: 'projet-e9263',
    authDomain: 'projet-e9263.firebaseapp.com',
    storageBucket: 'projet-e9263.firebasestorage.app',
    measurementId: 'G-XDTTLLNBW8',
  );

}